In [50]:
import pandas as pd
from IPython.display import display
bookstack_path2csv="/home/fedor/Projects/chatbot-mark-api/scripts/exported_data.csv"

df = pd.read_csv(bookstack_path2csv)

display(df.head())
display(df.info())
display(df.Chapter.value_counts())

,Chapter,Page,Content
0,МФК,Что такое МФК?,"МФК — это межфакультетские курсы, обязательные..."
1,МФК,Для чего введены МФК?,Одна из главных особенностей университетского ...
2,МФК,"У меня не было учебных курсов, связанных с тем...","Да, межфакультетские учебные курсы готовятся т..."
3,МФК,Для кого МФК обязательны?,"Для студентов, обучающихся по специальности «Ф..."
4,МФК,"Можно ли посещать МФК, если он для меня не обя...",Студент МГУ имеет право посещать любые лекцион...

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Chapter  118 non-null    object
 1   Page     118 non-null    object
 2   Content  117 non-null    object
dtypes: object(3)
memory usage: 2.9+ KB

None

Chapter
Обучение                           25
Профсоюз                           18
Стипендии и выплаты                17
МФК                                13
Инфраструктура и другие вопросы    11
Общежитие                           9
Пересдачи                           7
Академический отпуск                6
Учебная часть                       5
Дисциплинарные взыскания            4
Перевод на бюджет                   3
Name: count, dtype: int64

In [51]:
df.columns
df.rename(columns={'Content':'answer', 'Page': 'topic_name', 'Chapter':'Key words'}, inplace=True)
# df['id'] = 
df = df[['topic_name', 'answer', 'Key words']]
df.head()

,topic_name,answer,Key words
0,Что такое МФК?,"МФК — это межфакультетские курсы, обязательные...",МФК
1,Для чего введены МФК?,Одна из главных особенностей университетского ...,МФК
2,"У меня не было учебных курсов, связанных с тем...","Да, межфакультетские учебные курсы готовятся т...",МФК
3,Для кого МФК обязательны?,"Для студентов, обучающихся по специальности «Ф...",МФК
4,"Можно ли посещать МФК, если он для меня не обя...",Студент МГУ имеет право посещать любые лекцион...,МФК

In [52]:
display(df[df.answer.isna()])
df.loc[df.topic_name == "Календарь праздничных и выходных дней", "answer"] = 'График праздников и выходных'
df.iloc[69]

,topic_name,answer,Key words
69,Календарь праздничных и выходных дней,NaN,Инфраструктура и другие вопросы

topic_name    Календарь праздничных и выходных дней
answer                 График праздников и выходных
Key words           Инфраструктура и другие вопросы
Name: 69, dtype: object

In [53]:
df["answer"] = df["topic_name"] + " " + df['answer']

In [55]:
display(df.head())
display(df.iloc[69])
display(df.isna().sum())
df.to_excel("bookstack.xlsx")

,topic_name,answer,Key words
0,Что такое МФК?,Что такое МФК? МФК — это межфакультетские курс...,МФК
1,Для чего введены МФК?,Для чего введены МФК? Одна из главных особенно...,МФК
2,"У меня не было учебных курсов, связанных с тем...","У меня не было учебных курсов, связанных с тем...",МФК
3,Для кого МФК обязательны?,"Для кого МФК обязательны? Для студентов, обуча...",МФК
4,"Можно ли посещать МФК, если он для меня не обя...","Можно ли посещать МФК, если он для меня не обя...",МФК

topic_name                Календарь праздничных и выходных дней
answer        Календарь праздничных и выходных дней График п...
Key words                       Инфраструктура и другие вопросы
Name: 69, dtype: object

topic_name    0
answer        0
Key words     0
dtype: int64